name: Scheduled Merge from Upstream

on:
  schedule:
    - cron: '0 */6 * * *' # Runs every 6 hours
  workflow_dispatch:      # Allows you to run it manually

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required to fetch all history for the merge

      - name: Sync Upstream
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git remote add upstream https://github.com/LUC4N3X/stremio-leviathan-addon.git
          git fetch upstream
          # Merges the upstream main branch into your fork's main branch
          git checkout main
          git merge upstream/main --allow-unrelated-histories -m "Auto-sync from upstream" || echo "Conflict detected"
          git push origin main
